### ISSUE TITLE
Support string encryption？

### ISSUE THREAD

**Issue by df13954** [ratsan/dex2c#30]
This is an excellent project. According to the documentation, I successfully built a new APK. When using IDA to inspect stub.so, I noticed that all the strings inside are in plaintext. How can we hide these plaintext strings? By encrypting them, we can make the code harder to understand.

**Comment by AbhiTheModder** [comment]
Hi @df13954 ,

Thank you for your feedback! The feature you mentioned has already been implemented in #1. You can use it by giving it either `-p` or `--obfuscate` flag.

If you have any further questions or need assistance, feel free to ask!

Best regards,
Abhi
