### ISSUE TITLE
report an error

### ISSUE THREAD

**Issue by SedgeWarbler** [ratsan/dex2c#5]
![image](https://github.com/ratsan/dex2c/assets/32641989/ccb09c44-864c-4103-85a3-ddfa3b1e1731)
![image](https://github.com/ratsan/dex2c/assets/32641989/3cfd7ccd-b7e8-468e-ba1b-b6a834d6a8b4)
![image](https://github.com/ratsan/dex2c/assets/32641989/ade0d28b-10d1-4672-8db1-e39cdafb1aa9)

And it's been stuck here ever since

python version 3.8.1

**Comment by redragon14368** [comment]
You should filter packages instead of using **.*** in **filter.txt**
